version: '3.9'

services:

  rest_scraper:
    build:
      context: ./services
      dockerfile: rest_scraper/dockerfile
    env_file:
      - ./services/rest_scraper/prod.env
    entrypoint: ['/usr/src/rest_scraper/entrypoint.sh']
    ports:
      - 80:80
    depends_on:
      - elasticsearch
    restart: on-failure

  periodic_scraper:
    build:
      context: ./services
      dockerfile: periodic_scraper/dockerfile
    env_file:
      - ./services/periodic_scraper/prod.env
    entrypoint: ['/usr/src/periodic_scraper/entrypoint.sh']
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
    restart: on-failure

volumes:
   elasticsearch-data:
   kibana-data:
