version: '3.9'

services:

  data_collector:
    build:
      context: ./services/data_collector
      dockerfile: dockerfile
    env_file:
      - ./services/data_collector/data_collector.env
    entrypoint: ['/usr/src/data_collector/entrypoint.sh']
    ports:
      - 80:80
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
    restart: on-failure

volumes:
   elasticsearch-data:
   kibana-data:
