version: '3.9'

services:

  mongodb:
    image: mongo:latest
    volumes:
      - './services/mongodb/db:/data/db'
    expose:
      - 27017
    ports:
      - 27017:27017

  data_collector:
    build:
      context: ./services/data_collector
      dockerfile: Dockerfile
    env_file:
      - ./services/data_collector/data_collector.env
    entrypoint: ['/usr/src/data_collector/entrypoint.sh']
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - mongodb

  # grafana:
  #   image: grafana:latest
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000
