# pull official base image
FROM python:3.11.3

# install netcat
RUN apt-get update && \
    apt-get install -y netcat && \
    apt-get clean

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set working directory
WORKDIR /usr/src/rest_scraper

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/rest_scraper/requirements.txt
RUN pip install -r requirements.txt

# add app code
COPY . /usr/src/rest_scraper

# add common code
COPY ../common/ /usr/src/rest_scraper/src

# enable entrypoint
RUN chmod +x /usr/src/rest_scraper/entrypoint.sh
